add phone number to countries
angular-material-extensions/select-country pull request #40
Opened 2020-09-09 17:39 UTC by cedvdb

2020-09-09 17:41 UTC, cedvdb commented
I just saw you were asking for a PR for this in the issues. So I did it fast. if you want to add other things I just copy pasted the info from [here ](https://gist.github.com/Goles/3196253) and ran a forEach loop.

```
codes.forEach(code => {
   const found = phones.find(p => p.Iso2 === code.alpha2Code);
   if (found) {
      code.dial = found.Dial;
   }
});
```

2020-10-23 21:09 UTC, AnthonyNahas requested changes

2020-10-23 21:09 UTC, AnthonyNahas commented on projects/angular-material-extensions/select-country/src/lib/db.ts
>  export const COUNTRIES_DB: Country[] =
@cedvdb may you check the latest version `3.0.1` and adapt your code into the multiple i18n dbs ?

Thank you for your work

2021-03-06 18:45 UTC, essana3 commented
@cedvdb the gist you're using as reference for calling codes has some mistakes.

2021-03-07 20:55 UTC, essana3 commented
@AnthonyNahas I think this should be closed since it's already been added in 4.1.0

2021-03-07 22:24 UTC, closed without merging